[package]
name = "gtao-solo-lobby"
version = "1.0.5"
authors = ["Oscuro87"]
edition = "2021"
repository = "https://github.com/Oscuro87/gtao-solo-lobby/"

[[bin]]
name = "gtao-solo-lobby"
test = false
bench = false

[dependencies]
remoteprocess = "0.4.10"
winproc = "0.6.4"
